import { ThemeConfig } from "./types";

export const STYLE_PRESETS = [
  {
    name: "Glassmorphism",
    description: "Frosted glass effect with soft shadows",
    colors: {
      bgPrimary: "#0f172a",
      bgSecondary: "rgba(30, 41, 59, 0.7)",
      textPrimary: "#ffffff",
      textSecondary: "#94a3b8",
      accent: "#38bdf8",
      userBubble: "#38bdf8",
      aiBubble: "rgba(15, 23, 42, 0.5)",
      border: "rgba(255, 255, 255, 0.1)",
      backgroundOpacity: 0.2,
      backgroundImage: "https://images.unsplash.com/photo-1614850523296-d8c1af93d400?auto=format&fit=crop&q=80&w=1000"
    },
    borderRadius: "1.5rem",
    fontFamily: "Inter"
  },
  {
    name: "Cyberpunk",
    description: "High contrast neon and deep blacks",
    colors: {
      bgPrimary: "#050505",
      bgSecondary: "#111111",
      textPrimary: "#00ff00",
      textSecondary: "#008800",
      accent: "#ff00ff",
      userBubble: "#ff00ff",
      aiBubble: "#1a1a1a",
      border: "#00ff00",
      backgroundOpacity: 0.1,
      backgroundImage: "https://images.unsplash.com/photo-1550745165-9bc0b252726f?auto=format&fit=crop&q=80&w=1000"
    },
    borderRadius: "0px",
    fontFamily: "JetBrains Mono"
  },
  {
    name: "Aero",
    description: "Windows 7 inspired transparency",
    colors: {
      bgPrimary: "#0078d7",
      bgSecondary: "rgba(255, 255, 255, 0.2)",
      textPrimary: "#ffffff",
      textSecondary: "rgba(255, 255, 255, 0.7)",
      accent: "#ffffff",
      userBubble: "rgba(255, 255, 255, 0.3)",
      aiBubble: "rgba(0, 0, 0, 0.1)",
      border: "rgba(255, 255, 255, 0.4)",
      backgroundOpacity: 0.4,
      backgroundImage: "https://images.unsplash.com/photo-1541450805268-4822a3a774ca?auto=format&fit=crop&q=80&w=1000"
    },
    borderRadius: "8px",
    fontFamily: "Inter"
  },
  {
    name: "Dracula",
    description: "The classic dark theme for developers",
    colors: {
      bgPrimary: "#282a36",
      bgSecondary: "#44475a",
      textPrimary: "#f8f8f2",
      textSecondary: "#6272a4",
      accent: "#bd93f9",
      userBubble: "#ff79c6",
      aiBubble: "#282a36",
      border: "#44475a",
    },
    borderRadius: "0.5rem",
    fontFamily: "JetBrains Mono"
  },
  {
    name: "Nordic",
    description: "Arctic cold and clean aesthetic",
    colors: {
      bgPrimary: "#2e3440",
      bgSecondary: "#3b4252",
      textPrimary: "#eceff4",
      textSecondary: "#d8dee9",
      accent: "#88c0d0",
      userBubble: "#81a1c1",
      aiBubble: "#2e3440",
      border: "#4c566a",
    },
    borderRadius: "1rem",
    fontFamily: "Inter"
  },
  {
    name: "Synthwave",
    description: "Outrun the sunset with 80s vibes",
    colors: {
      bgPrimary: "#241734",
      bgSecondary: "#2e2141",
      textPrimary: "#ff71ce",
      textSecondary: "#b967ff",
      accent: "#01cdfe",
      userBubble: "#05ffa1",
      aiBubble: "#241734",
      border: "#ff71ce",
      backgroundOpacity: 0.2,
      backgroundImage: "https://images.unsplash.com/photo-1614850523296-d8c1af93d400?auto=format&fit=crop&q=80&w=1000"
    },
    borderRadius: "1.5rem",
    fontFamily: "Inter"
  },
  {
    name: "Neumorphism",
    description: "Soft UI with organic shadows",
    colors: {
      bgPrimary: "#e0e5ec",
      bgSecondary: "#e0e5ec",
      textPrimary: "#31344b",
      textSecondary: "#44476a",
      accent: "#6d5dfc",
      userBubble: "#e0e5ec",
      aiBubble: "#e0e5ec",
      border: "#ffffff",
    },
    borderRadius: "2rem",
    fontFamily: "Inter"
  },
  {
    name: "Midnight Pro",
    description: "Deep blue professional dark mode",
    colors: {
      bgPrimary: "#020617",
      bgSecondary: "#0f172a",
      textPrimary: "#f8fafc",
      textSecondary: "#94a3b8",
      accent: "#3b82f6",
      userBubble: "#3b82f6",
      aiBubble: "#1e293b",
      border: "#334155",
    },
    borderRadius: "1rem",
    fontFamily: "Inter"
  },
  {
    name: "Solarized",
    description: "Warm, low-contrast reading experience",
    colors: {
      bgPrimary: "#fdf6e3",
      bgSecondary: "#eee8d5",
      textPrimary: "#586e75",
      textSecondary: "#93a1a1",
      accent: "#268bd2",
      userBubble: "#268bd2",
      aiBubble: "#eee8d5",
      border: "#d33682",
    },
    borderRadius: "0.5rem",
    fontFamily: "Georgia"
  },
  {
    name: "Matrix",
    description: "Digital rain aesthetic",
    colors: {
      bgPrimary: "#000000",
      bgSecondary: "#000000",
      textPrimary: "#00ff41",
      textSecondary: "#008f11",
      accent: "#003b00",
      userBubble: "#003b00",
      aiBubble: "#000000",
      border: "#00ff41",
    },
    borderRadius: "0px",
    fontFamily: "JetBrains Mono"
  }
];

export const DEFAULT_THEMES: ThemeConfig[] = [
  {
    id: "standard-dark",
    name: "Standard Dark",
    author: "SkinCraft",
    price: 0,
    isPurchased: true,
    canCustomize: true,
    fontFamily: "Inter",
    borderRadius: "1rem",
    musicWidget: { provider: "none", isVisible: false, isUnlocked: true },
    colors: {
      bgPrimary: "#171717",
      bgSecondary: "#212121",
      textPrimary: "#ececec",
      textSecondary: "#b4b4b4",
      accent: "#ab68ff",
      userBubble: "#2f2f2f",
      aiBubble: "transparent",
      border: "#2f2f2f",
    },
  },
  {
    id: "default-dark",
    name: "Midnight Pro",
    author: "SkinCraft",
    price: 0,
    fontFamily: "Inter",
    borderRadius: "0.75rem",
    musicWidget: { provider: "none", isVisible: false, isUnlocked: false },
    colors: {
      bgPrimary: "#0f172a",
      bgSecondary: "#1e293b",
      textPrimary: "#f8fafc",
      textSecondary: "#94a3b8",
      accent: "#3b82f6",
      userBubble: "#3b82f6",
      aiBubble: "#334155",
      border: "#334155",
    },
  },
  {
    id: "cyberpunk",
    name: "Neon Nights",
    author: "CyberArtist",
    price: 4.99,
    fontFamily: "JetBrains Mono",
    borderRadius: "0px",
    musicWidget: { provider: "none", isVisible: false, isUnlocked: false },
    colors: {
      bgPrimary: "#050505",
      bgSecondary: "#1a1a1a",
      textPrimary: "#00ff00",
      textSecondary: "#008800",
      accent: "#ff00ff",
      userBubble: "#ff00ff",
      aiBubble: "#111111",
      border: "#00ff00",
    },
  },
  {
    id: "minimal-light",
    name: "Paper White",
    author: "Minimalist",
    price: 2.99,
    fontFamily: "Georgia",
    borderRadius: "1.5rem",
    musicWidget: { provider: "none", isVisible: false, isUnlocked: false },
    colors: {
      bgPrimary: "#ffffff",
      bgSecondary: "#f8f9fa",
      textPrimary: "#1a1a1a",
      textSecondary: "#666666",
      accent: "#000000",
      userBubble: "#000000",
      aiBubble: "#f0f0f0",
      border: "#e0e0e0",
    },
  },
  {
    id: "forest-whisper",
    name: "Forest Whisper",
    author: "NatureLover",
    price: 0,
    fontFamily: "Inter",
    borderRadius: "1rem",
    musicWidget: { provider: "none", isVisible: false, isUnlocked: false },
    colors: {
      bgPrimary: "#064e3b",
      bgSecondary: "#065f46",
      textPrimary: "#ecfdf5",
      textSecondary: "#a7f3d0",
      accent: "#10b981",
      userBubble: "#059669",
      aiBubble: "#064e3b",
      border: "#065f46",
    },
  },
  {
    id: "solar-flare",
    name: "Solar Flare",
    author: "StarGazer",
    price: 3.50,
    fontFamily: "Inter",
    borderRadius: "4px",
    musicWidget: { provider: "none", isVisible: false, isUnlocked: false },
    colors: {
      bgPrimary: "#450a0a",
      bgSecondary: "#7c2d12",
      textPrimary: "#fef3c7",
      textSecondary: "#fde68a",
      accent: "#f59e0b",
      userBubble: "#ea580c",
      aiBubble: "#450a0a",
      border: "#7c2d12",
    },
  },
  {
    id: "deep-sea",
    name: "Deep Sea",
    author: "Oceanic",
    price: 0,
    fontFamily: "Inter",
    borderRadius: "2rem",
    musicWidget: { provider: "none", isVisible: false, isUnlocked: false },
    colors: {
      bgPrimary: "#082f49",
      bgSecondary: "#0c4a6e",
      textPrimary: "#f0f9ff",
      textSecondary: "#bae6fd",
      accent: "#0ea5e9",
      userBubble: "#0284c7",
      aiBubble: "#082f49",
      border: "#0c4a6e",
    },
  },
  {
    id: "lavender-dream",
    name: "Lavender Dream",
    author: "DreamyDev",
    price: 1.99,
    fontFamily: "Inter",
    borderRadius: "12px",
    musicWidget: { provider: "none", isVisible: false, isUnlocked: false },
    colors: {
      bgPrimary: "#2e1065",
      bgSecondary: "#4c1d95",
      textPrimary: "#f5f3ff",
      textSecondary: "#ddd6fe",
      accent: "#8b5cf6",
      userBubble: "#7c3aed",
      aiBubble: "#2e1065",
      border: "#4c1d95",
    },
  },
  {
    id: "brutalist-red",
    name: "Brutalist Red",
    author: "Modernist",
    price: 5.00,
    fontFamily: "JetBrains Mono",
    borderRadius: "0px",
    musicWidget: { provider: "none", isVisible: false, isUnlocked: false },
    colors: {
      bgPrimary: "#000000",
      bgSecondary: "#111111",
      textPrimary: "#ffffff",
      textSecondary: "#999999",
      accent: "#ff0000",
      userBubble: "#ff0000",
      aiBubble: "#222222",
      border: "#ffffff",
    },
  },
  {
    id: "vaporwave",
    name: "Vaporwave 84",
    author: "RetroWave",
    price: 3.99,
    fontFamily: "Inter",
    borderRadius: "1.5rem",
    musicWidget: { provider: "none", isVisible: false, isUnlocked: false },
    colors: {
      bgPrimary: "#2d0a31",
      bgSecondary: "#4a154b",
      textPrimary: "#ff71ce",
      textSecondary: "#b967ff",
      accent: "#01cdfe",
      userBubble: "#05ffa1",
      aiBubble: "#2d0a31",
      border: "#b967ff",
      backgroundImage: "https://images.unsplash.com/photo-1614850523296-d8c1af93d400?auto=format&fit=crop&q=80&w=1000",
      backgroundOpacity: 0.3
    },
  },
  {
    id: "minecraft",
    name: "Block World",
    author: "CraftMaster",
    price: 0,
    fontFamily: "JetBrains Mono",
    borderRadius: "0px",
    musicWidget: { provider: "none", isVisible: false, isUnlocked: false },
    colors: {
      bgPrimary: "#4a7023",
      bgSecondary: "#354a21",
      textPrimary: "#ffffff",
      textSecondary: "#bcbcbc",
      accent: "#8b4513",
      userBubble: "#8b4513",
      aiBubble: "#4a7023",
      border: "#354a21",
      backgroundImage: "https://images.unsplash.com/photo-1587573089734-09cb69c0f2b4?auto=format&fit=crop&q=80&w=1000",
      backgroundOpacity: 0.2
    },
  },
  {
    id: "galactic-empire",
    name: "Imperial Command",
    author: "VaderDev",
    price: 5.99,
    fontFamily: "Inter",
    borderRadius: "4px",
    musicWidget: { provider: "none", isVisible: false, isUnlocked: false },
    colors: {
      bgPrimary: "#1a1a1a",
      bgSecondary: "#2a2a2a",
      textPrimary: "#ffffff",
      textSecondary: "#999999",
      accent: "#ff0000",
      userBubble: "#ff0000",
      aiBubble: "#111111",
      border: "#333333",
    },
  },
  {
    id: "retro-arcade",
    name: "Arcade Mania",
    author: "PixelPioneer",
    price: 2.50,
    fontFamily: "JetBrains Mono",
    borderRadius: "0px",
    musicWidget: { provider: "none", isVisible: false, isUnlocked: false },
    colors: {
      bgPrimary: "#000000",
      bgSecondary: "#000044",
      textPrimary: "#ffff00",
      textSecondary: "#ff00ff",
      accent: "#00ffff",
      userBubble: "#00ffff",
      aiBubble: "#000000",
      border: "#ffff00",
    },
  },
  {
    id: "ghibli-sky",
    name: "Spirit Skies",
    author: "StudioFan",
    price: 4.50,
    fontFamily: "Georgia",
    borderRadius: "2rem",
    musicWidget: { provider: "none", isVisible: false, isUnlocked: false },
    colors: {
      bgPrimary: "#87ceeb",
      bgSecondary: "#f0f8ff",
      textPrimary: "#2f4f4f",
      textSecondary: "#4682b4",
      accent: "#ffffff",
      userBubble: "#ffffff",
      aiBubble: "#e0ffff",
      border: "#add8e6",
      backgroundImage: "https://images.unsplash.com/photo-1534067783941-51c9c23ecefd?auto=format&fit=crop&q=80&w=1000",
      backgroundOpacity: 0.4
    },
  },
  {
    id: "roblox",
    name: "Blox Style",
    author: "Robloxian",
    price: 0,
    fontFamily: "Inter",
    borderRadius: "0.5rem",
    musicWidget: { provider: "none", isVisible: false, isUnlocked: false },
    colors: {
      bgPrimary: "#ffffff",
      bgSecondary: "#e3e3e3",
      textPrimary: "#000000",
      textSecondary: "#666666",
      accent: "#e2231a",
      userBubble: "#e2231a",
      aiBubble: "#f2f2f2",
      border: "#cccccc",
    },
  },
  {
    id: "cod-tactical",
    name: "Tactical Ops",
    author: "GhostOperator",
    price: 4.99,
    fontFamily: "JetBrains Mono",
    borderRadius: "2px",
    musicWidget: { provider: "none", isVisible: false, isUnlocked: false },
    colors: {
      bgPrimary: "#1a1c19",
      bgSecondary: "#242622",
      textPrimary: "#d1d1d1",
      textSecondary: "#8a8a8a",
      accent: "#4e5945",
      userBubble: "#4e5945",
      aiBubble: "#1a1c19",
      border: "#3a3d37",
      backgroundImage: "https://images.unsplash.com/photo-1509198397868-475647b2a1e5?auto=format&fit=crop&q=80&w=1000",
      backgroundOpacity: 0.15
    },
  },
  {
    id: "anime-dragon",
    name: "Dragon Spirit",
    author: "Z-Warrior",
    price: 3.50,
    fontFamily: "Inter",
    borderRadius: "1rem",
    musicWidget: { provider: "none", isVisible: false, isUnlocked: false },
    colors: {
      bgPrimary: "#ff8c00",
      bgSecondary: "#e67e00",
      textPrimary: "#ffffff",
      textSecondary: "#ffd700",
      accent: "#0000ff",
      userBubble: "#0000ff",
      aiBubble: "#ff8c00",
      border: "#cc7000",
    },
  },
  {
    id: "anime-ninja",
    name: "Ninja Way",
    author: "HokageDev",
    price: 2.99,
    fontFamily: "Inter",
    borderRadius: "0.5rem",
    musicWidget: { provider: "none", isVisible: false, isUnlocked: false },
    colors: {
      bgPrimary: "#1a1a1a",
      bgSecondary: "#2a2a2a",
      textPrimary: "#ff6600",
      textSecondary: "#8a8a8a",
      accent: "#0066cc",
      userBubble: "#0066cc",
      aiBubble: "#1a1a1a",
      border: "#333333",
      backgroundImage: "https://images.unsplash.com/photo-1578632292335-df3abbb0d586?auto=format&fit=crop&q=80&w=1000",
      backgroundOpacity: 0.2
    },
  },
  {
    id: "the-merc",
    name: "The Merc",
    author: "ComicFan",
    price: 4.99,
    fontFamily: "Inter",
    borderRadius: "0.5rem",
    musicWidget: { provider: "none", isVisible: false, isUnlocked: true },
    colors: {
      bgPrimary: "#7f1d1d",
      bgSecondary: "#450a0a",
      textPrimary: "#ffffff",
      textSecondary: "#f87171",
      accent: "#000000",
      userBubble: "#000000",
      aiBubble: "#7f1d1d",
      border: "#450a0a",
      backgroundImage: "https://picsum.photos/seed/deadpool/1920/1080?blur=2",
      backgroundOpacity: 0.2
    },
  },
  {
    id: "comic-blast",
    name: "Boom Pow!",
    author: "PopArtist",
    price: 3.99,
    fontFamily: "Inter",
    borderRadius: "0px",
    musicWidget: { provider: "none", isVisible: false, isUnlocked: true },
    colors: {
      bgPrimary: "#fde047",
      bgSecondary: "#facc15",
      textPrimary: "#1e3a8a",
      textSecondary: "#1d4ed8",
      accent: "#ef4444",
      userBubble: "#ef4444",
      aiBubble: "#fde047",
      border: "#1e3a8a",
      backgroundImage: "https://picsum.photos/seed/comic/1920/1080",
      backgroundOpacity: 0.15
    },
  },
  {
    id: "neon-predator",
    name: "Neon Predator",
    author: "ElectricWild",
    price: 5.50,
    fontFamily: "JetBrains Mono",
    borderRadius: "1rem",
    musicWidget: { provider: "none", isVisible: false, isUnlocked: true },
    colors: {
      bgPrimary: "#020617",
      bgSecondary: "#0f172a",
      textPrimary: "#38bdf8",
      textSecondary: "#818cf8",
      accent: "#f43f5e",
      userBubble: "#f43f5e",
      aiBubble: "#020617",
      border: "#38bdf8",
      backgroundImage: "https://picsum.photos/seed/wolf/1920/1080?blur=3",
      backgroundOpacity: 0.3
    },
  },
  {
    id: "cyber-tunnel",
    name: "Cyber Tunnel",
    author: "GridRunner",
    price: 4.50,
    fontFamily: "JetBrains Mono",
    borderRadius: "4px",
    musicWidget: { provider: "none", isVisible: false, isUnlocked: true },
    colors: {
      bgPrimary: "#000000",
      bgSecondary: "#111111",
      textPrimary: "#06b6d4",
      textSecondary: "#0891b2",
      accent: "#d946ef",
      userBubble: "#d946ef",
      aiBubble: "#000000",
      border: "#06b6d4",
      backgroundImage: "https://picsum.photos/seed/tunnel/1920/1080",
      backgroundOpacity: 0.4
    },
  },
  {
    id: "vinyl-doodles",
    name: "Vinyl Doodles",
    author: "LoFiVibes",
    price: 2.99,
    fontFamily: "Georgia",
    borderRadius: "1.5rem",
    musicWidget: { provider: "spotify", isVisible: true, isUnlocked: true, playlistId: "37i9dQZF1DWWQRwui0Ex2X" },
    colors: {
      bgPrimary: "#fafaf9",
      bgSecondary: "#f5f5f4",
      textPrimary: "#44403c",
      textSecondary: "#78716c",
      accent: "#d97706",
      userBubble: "#d97706",
      aiBubble: "#e7e5e4",
      border: "#d6d3d1",
      backgroundImage: "https://picsum.photos/seed/music/1920/1080?grayscale",
      backgroundOpacity: 0.1
    },
  },
  {
    id: "electric-mouse",
    name: "Electric Mouse",
    author: "PikaDev",
    price: 0,
    fontFamily: "Inter",
    borderRadius: "1rem",
    musicWidget: { provider: "none", isVisible: false, isUnlocked: true },
    colors: {
      bgPrimary: "#facc15",
      bgSecondary: "#eab308",
      textPrimary: "#1e3a8a",
      textSecondary: "#1d4ed8",
      accent: "#ef4444",
      userBubble: "#1e3a8a",
      aiBubble: "#facc15",
      border: "#ca8a04",
    },
  },
  {
    id: "void-stalker",
    name: "Void Stalker",
    author: "RavenLord",
    price: 5.99,
    fontFamily: "JetBrains Mono",
    borderRadius: "2px",
    musicWidget: { provider: "none", isVisible: false, isUnlocked: true },
    colors: {
      bgPrimary: "#1e1b4b",
      bgSecondary: "#312e81",
      textPrimary: "#c084fc",
      textSecondary: "#a855f7",
      accent: "#000000",
      userBubble: "#000000",
      aiBubble: "#1e1b4b",
      border: "#4c1d95",
      backgroundImage: "https://picsum.photos/seed/raven/1920/1080?blur=5",
      backgroundOpacity: 0.2
    },
  },
  {
    id: "masters-wisdom",
    name: "Master's Wisdom",
    author: "ForceUser",
    price: 4.50,
    fontFamily: "Inter",
    borderRadius: "2rem",
    musicWidget: { provider: "none", isVisible: false, isUnlocked: true },
    colors: {
      bgPrimary: "#064e3b",
      bgSecondary: "#065f46",
      textPrimary: "#fde047",
      textSecondary: "#facc15",
      accent: "#10b981",
      userBubble: "#059669",
      aiBubble: "#064e3b",
      border: "#065f46",
      backgroundImage: "https://picsum.photos/seed/yoda/1920/1080",
      backgroundOpacity: 0.2
    },
  },
  {
    id: "liquid-aurora",
    name: "Liquid Aurora",
    author: "FluidArtist",
    price: 3.50,
    fontFamily: "Inter",
    borderRadius: "1.5rem",
    musicWidget: { provider: "none", isVisible: false, isUnlocked: true },
    colors: {
      bgPrimary: "#0f172a",
      bgSecondary: "#1e293b",
      textPrimary: "#f472b6",
      textSecondary: "#fb7185",
      accent: "#818cf8",
      userBubble: "#818cf8",
      aiBubble: "#0f172a",
      border: "#334155",
      backgroundImage: "https://picsum.photos/seed/aurora/1920/1080",
      backgroundOpacity: 0.3
    },
  },
  {
    id: "mechanical-soul",
    name: "Mechanical Soul",
    author: "CyberPanther",
    price: 5.99,
    fontFamily: "JetBrains Mono",
    borderRadius: "0px",
    musicWidget: { provider: "none", isVisible: false, isUnlocked: true },
    colors: {
      bgPrimary: "#0a0a0a",
      bgSecondary: "#171717",
      textPrimary: "#fbbf24",
      textSecondary: "#f59e0b",
      accent: "#404040",
      userBubble: "#404040",
      aiBubble: "#0a0a0a",
      border: "#fbbf24",
      backgroundImage: "https://picsum.photos/seed/panther/1920/1080",
      backgroundOpacity: 0.2
    },
  },
];
