import { ThemeConfig } from "./types";

export const DEFAULT_THEMES: ThemeConfig[] = [
  {
    id: "standard-dark",
    name: "Standard Dark",
    author: "SkinCraft",
    price: 0,
    fontFamily: "Inter",
    borderRadius: "1rem",
    colors: {
      bgPrimary: "#171717",
      bgSecondary: "#212121",
      textPrimary: "#ececec",
      textSecondary: "#b4b4b4",
      accent: "#ab68ff",
      userBubble: "#2f2f2f",
      aiBubble: "transparent",
      border: "#2f2f2f",
    },
  },
  {
    id: "default-dark",
    name: "Midnight Pro",
    author: "SkinCraft",
    price: 0,
    fontFamily: "Inter",
    borderRadius: "0.75rem",
    colors: {
      bgPrimary: "#0f172a",
      bgSecondary: "#1e293b",
      textPrimary: "#f8fafc",
      textSecondary: "#94a3b8",
      accent: "#3b82f6",
      userBubble: "#3b82f6",
      aiBubble: "#334155",
      border: "#334155",
    },
  },
  {
    id: "cyberpunk",
    name: "Neon Nights",
    author: "CyberArtist",
    price: 4.99,
    fontFamily: "JetBrains Mono",
    borderRadius: "0px",
    colors: {
      bgPrimary: "#050505",
      bgSecondary: "#1a1a1a",
      textPrimary: "#00ff00",
      textSecondary: "#008800",
      accent: "#ff00ff",
      userBubble: "#ff00ff",
      aiBubble: "#111111",
      border: "#00ff00",
    },
  },
  {
    id: "minimal-light",
    name: "Paper White",
    author: "Minimalist",
    price: 2.99,
    fontFamily: "Georgia",
    borderRadius: "1.5rem",
    colors: {
      bgPrimary: "#ffffff",
      bgSecondary: "#f8f9fa",
      textPrimary: "#1a1a1a",
      textSecondary: "#666666",
      accent: "#000000",
      userBubble: "#000000",
      aiBubble: "#f0f0f0",
      border: "#e0e0e0",
    },
  },
  {
    id: "forest-whisper",
    name: "Forest Whisper",
    author: "NatureLover",
    price: 0,
    fontFamily: "Inter",
    borderRadius: "1rem",
    colors: {
      bgPrimary: "#064e3b",
      bgSecondary: "#065f46",
      textPrimary: "#ecfdf5",
      textSecondary: "#a7f3d0",
      accent: "#10b981",
      userBubble: "#059669",
      aiBubble: "#064e3b",
      border: "#065f46",
    },
  },
  {
    id: "solar-flare",
    name: "Solar Flare",
    author: "StarGazer",
    price: 3.50,
    fontFamily: "Inter",
    borderRadius: "4px",
    colors: {
      bgPrimary: "#450a0a",
      bgSecondary: "#7c2d12",
      textPrimary: "#fef3c7",
      textSecondary: "#fde68a",
      accent: "#f59e0b",
      userBubble: "#ea580c",
      aiBubble: "#450a0a",
      border: "#7c2d12",
    },
  },
  {
    id: "deep-sea",
    name: "Deep Sea",
    author: "Oceanic",
    price: 0,
    fontFamily: "Inter",
    borderRadius: "2rem",
    colors: {
      bgPrimary: "#082f49",
      bgSecondary: "#0c4a6e",
      textPrimary: "#f0f9ff",
      textSecondary: "#bae6fd",
      accent: "#0ea5e9",
      userBubble: "#0284c7",
      aiBubble: "#082f49",
      border: "#0c4a6e",
    },
  },
  {
    id: "lavender-dream",
    name: "Lavender Dream",
    author: "DreamyDev",
    price: 1.99,
    fontFamily: "Inter",
    borderRadius: "12px",
    colors: {
      bgPrimary: "#2e1065",
      bgSecondary: "#4c1d95",
      textPrimary: "#f5f3ff",
      textSecondary: "#ddd6fe",
      accent: "#8b5cf6",
      userBubble: "#7c3aed",
      aiBubble: "#2e1065",
      border: "#4c1d95",
    },
  },
  {
    id: "brutalist-red",
    name: "Brutalist Red",
    author: "Modernist",
    price: 5.00,
    fontFamily: "JetBrains Mono",
    borderRadius: "0px",
    colors: {
      bgPrimary: "#000000",
      bgSecondary: "#111111",
      textPrimary: "#ffffff",
      textSecondary: "#999999",
      accent: "#ff0000",
      userBubble: "#ff0000",
      aiBubble: "#222222",
      border: "#ffffff",
    },
  },
];
